spring:
  datasource:
    url: jdbc:mysql://localhost:3306/geometry
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
#    drop-first: true